### ISSUE TITLE
Could you please provide test code for our repetition?

### ISSUE THREAD

**Issue by 2508756189** [lwgkzl/MultiESC#4]
After following your training steps, I don't know how to test it.

**Comment by YiCheng98** [comment]
If you want to conduct evaluation only without training, you could simply do this by modifying lines 258~260  in generate_sentence.py as follows:

```
if not args.do_train=="False":
    train_result = trainer.train()
    trainer.save_model()  # Saves the tokenizer too for easy upload
    metrics = train_result.metrics
```
Then, you could set `--do_train=False` and set `model_name_or_path` to your assessed checkpoint for evaluation. The evaluation results of the considered metrics will be displayed after running.

The current codes do not directly output all the generation results. One feasible way to get the generation results is by modifying the `compute_metrics` function in generate_sentence.py. For example, you might add the following codes in this function at line 158:
```
    generation_data = []
    for i in range(len(decoded_labels)):
        generation_data.append({"generation": decoded_preds[i], "gold_response": decoded_labels[i]})
    with open(f"generation_results.json", 'w', encoding="utf-8") as f:
        f.write(json.dumps(generation_data))
```

**Comment by zkq125** [comment]
Which version of the author's bart-base is used, the base version I use appears ：local variable 'history_seqence_hidden' referenced before assignment，Cannot continue because history_ids is None while running。Can you provide me with a bart-base link?
